// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi56VZoMVbPI_Lqrh4qV2afgB32ynLdMw',
    appId: '1:60849647234:web:101514cf78259862544e9b',
    messagingSenderId: '60849647234',
    projectId: 'notelist-mobdev-project',
    authDomain: 'notelist-mobdev-project.firebaseapp.com',
    storageBucket: 'notelist-mobdev-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPMm4qc738eDYXAYasFw4-PvX9mlfYThQ',
    appId: '1:60849647234:android:55f72d53b3ec50d7544e9b',
    messagingSenderId: '60849647234',
    projectId: 'notelist-mobdev-project',
    storageBucket: 'notelist-mobdev-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUBEen44UXaxJFvDm3EbcJWhVv4Yrq10',
    appId: '1:60849647234:ios:ca3a70e89c26e4c8544e9b',
    messagingSenderId: '60849647234',
    projectId: 'notelist-mobdev-project',
    storageBucket: 'notelist-mobdev-project.appspot.com',
    iosBundleId: 'bf.dimdigital.notelist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxUBEen44UXaxJFvDm3EbcJWhVv4Yrq10',
    appId: '1:60849647234:ios:ca3a70e89c26e4c8544e9b',
    messagingSenderId: '60849647234',
    projectId: 'notelist-mobdev-project',
    storageBucket: 'notelist-mobdev-project.appspot.com',
    iosBundleId: 'bf.dimdigital.notelist',
  );
}
